compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://npm.dev.wixpress.com/"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
